import { describe, it, expect, vi, beforeEach } from 'vitest';
import { createRequire } from 'module';

const require = createRequire(import.meta.url);
const marked = require('../marked.min.js');

// Mock global variables and chrome API
global.marked = marked;
global.chrome = {
  devtools: {
    inspectedWindow: {
      eval: vi.fn()
    }
  },
  tabs: {
    create: vi.fn()
  },
  runtime: {
    onMessage: {
      addListener: vi.fn()
    },
    getURL: vi.fn()
  },
  storage: {
    session: {
      get: vi.fn().mockResolvedValue({}),
      set: vi.fn().mockResolvedValue({})
    },
    local: {
      get: vi.fn().mockResolvedValue({}),
      set: vi.fn().mockResolvedValue({}),
      remove: vi.fn().mockResolvedValue({})
    }
  }
};

// Mock document/window functions used in chat.js
global.document = {
  addEventListener: vi.fn(),
  querySelector: vi.fn().mockReturnValue({
    addEventListener: vi.fn(),
    classList: { contains: vi.fn().mockReturnValue(false) }
  }),
  getElementById: vi.fn().mockReturnValue({
    addEventListener: vi.fn(),
    classList: { remove: vi.fn() }
  })
};
global.window = {
  addEventListener: vi.fn(),
  open: vi.fn()
};

global.normalizeSelector = (sel) => sel ? sel.trim() : "";
global.useCasesCache = [];
global.highlightCode = (code, lang) => code;

const { renderDinoResponse, escapeHtmlForChat } = require('../chat.js');

describe('chat.js - Link Rendering and Event Binding', () => {
  let container;
  let boundEvents;
  let createdLinks;
  let isInsideCodeBlock = false;

  beforeEach(() => {
    vi.clearAllMocks();
    boundEvents = [];
    createdLinks = [];
    isInsideCodeBlock = false;
    
    // Create a mock DOM container
    container = {
      _innerHTML: '',
      set innerHTML(val) {
        this._innerHTML = val;
      },
      get innerHTML() {
        return this._innerHTML;
      },
      querySelectorAll: vi.fn().mockImplementation((query) => {
        const elements = [];
        const aRegex = /<a\s+href="([^"]+)"[^>]*>(.*?)<\/a>/g;
        let match;
        while ((match = aRegex.exec(container._innerHTML)) !== null) {
          const href = match[1];
          const label = match[2];
          
          if (query === 'a[href^="inspect:"]' && href.startsWith('inspect:')) {
            elements.push(createMockLink(href, label));
          } else if (query === 'a[href^="suggest:"]' && href.startsWith('suggest:')) {
            elements.push(createMockLink(href, label));
          } else if (query === 'a[href]') {
            elements.push(createMockLink(href, label));
          }
        }
        console.log(`Query: ${query}, returned: ${elements.length} elements`);
        return elements;
      })
    };
  });

  function createMockLink(href, label) {
    const attrs = { href };
    const link = {
      className: '',
      style: {},
      getAttribute: (name) => attrs[name],
      removeAttribute: (name) => { delete attrs[name]; },
      addEventListener: (event, handler) => {
        boundEvents.push({ event, handler, link });
      },
      closest: (sel) => {
        if (sel === 'pre, code' && isInsideCodeBlock) return {};
        return null;
      },
      parentElement: {
        querySelector: vi.fn().mockImplementation((query) => {
          // If we query suggest link, check if suggest link is in innerHTML
          if (query === 'a[href^="suggest:"]') {
            return container._innerHTML.includes('href="suggest:') ? {} : null;
          }
          return null;
        })
      }
    };
    createdLinks.push(link);
    return link;
  }

  it('should correctly preprocess and parse suggest and inspect links', () => {
    const content = "[👀 Inspect Focus Styles](inspect:.elementor-widget-button a) [🛠️ Check Heading Hierarchy](inspect:h1, h2, h3, h4) [🚨 Scan Live Regions](inspect:[aria-live]) [✨ Apply Focus Fix](suggest:Add a high-contrast focus-visible outline)";
    
    renderDinoResponse(content, container);

    // Verify HTML structure generated by marked
    expect(container.innerHTML).toContain('href="inspect:.elementor-widget-button a"');
    expect(container.innerHTML).toContain('href="inspect:h1, h2, h3, h4"');
    expect(container.innerHTML).toContain('href="inspect:[aria-live]"');
    expect(container.innerHTML).toContain('href="suggest:Add a high-contrast focus-visible outline"');
  });

  it('should bind click handlers and style links in suggestion group correctly', () => {
    const content = "[👀 Inspect Focus Styles](inspect:.elementor-widget-button a) [✨ Apply Focus Fix](suggest:Add a high-contrast focus-visible outline)";
    
    renderDinoResponse(content, container);

    // Should bind click events to links (3 for inspect, 1 for suggest)
    expect(boundEvents.length).toBe(4);

    const inspectEvent = boundEvents.find(e => e.event === 'click' && e.link.parentElement.querySelector('a[href^="suggest:"]'));
    expect(inspectEvent).toBeDefined();
    
    // Inspect link should get suggestion button styling class since it's grouped with a suggestion button
    expect(inspectEvent.link.className).toBe('chat-suggest-btn');
  });

  it('should handle decoding of encoded characters in selector / suggestion text', () => {
    const content = "[👀 Inspect Focus Styles](inspect:.elementor-widget-button%20a)";
    
    renderDinoResponse(content, container);
    
    expect(boundEvents.length).toBe(3);
    const inspectEvent = boundEvents.find(e => e.event === 'click');
    
    // Trigger the click event handler
    const mockEvent = { preventDefault: vi.fn(), stopPropagation: vi.fn() };
    inspectEvent.handler(mockEvent);
    
    // Verify eval was called with the decoded selector
    expect(global.chrome.devtools.inspectedWindow.eval).toHaveBeenCalled();
    const evalCode = global.chrome.devtools.inspectedWindow.eval.mock.calls[0][0];
    expect(evalCode).toContain('.elementor-widget-button a');
  });

  it('should not crash if inspect link contains malformed URI percent-encoding', () => {
    const content = "[this element](inspect:div#main > %)";
    
    // This should run without throwing URIError: URI malformed
    expect(() => {
      renderDinoResponse(content, container);
    }).not.toThrow();
  });

  it('should not crash on incomplete suggest link', () => {
    const content = "[⚡ Optimize Markdown Images](suggest:";
    expect(() => {
      renderDinoResponse(content, container);
    }).not.toThrow();
  });

  it('should not crash on any prefix of a streaming response containing links and percentages', () => {
    const responseText = "Over 51.7% of the CSS downloaded on this page is completely unused! [⚡ Optimize Markdown Images](suggest:Optimize Markdown Images)";
    for (let i = 1; i <= responseText.length; i++) {
      const prefix = responseText.substring(0, i);
      expect(() => {
        renderDinoResponse(prefix, container);
        renderDinoResponse(prefix, container, { streaming: true });
      }).not.toThrow(`Failed on prefix index ${i}: "${prefix}"`);
    }
  });

  it('should not bind listeners while streaming, but style links and strip hrefs', () => {
    const content = "[👀 Inspect Focus Styles](inspect:.elementor-widget-button a) [✨ Apply Focus Fix](suggest:Add a high-contrast focus-visible outline)";

    renderDinoResponse(content, container, { streaming: true });

    expect(boundEvents.length).toBe(0);
    expect(createdLinks.length).toBe(2);
    const classNames = createdLinks.map(l => l.className).sort();
    expect(classNames).toEqual(['chat-suggest-btn', 'target-link-btn']);
    // hrefs are stripped so clicks cannot navigate the panel mid-stream
    createdLinks.forEach(link => {
      expect(link.getAttribute('href')).toBeUndefined();
    });
  });

  it('should not bind click handlers or style links that are inside pre or code tags', () => {
    isInsideCodeBlock = true;
    const content = "[👀 Inspect Focus Styles](inspect:.elementor-widget-button a) [✨ Apply Focus Fix](suggest:Add a high-contrast focus-visible outline)";
    
    renderDinoResponse(content, container);
    
    // Should not bind any events since closest('pre, code') returns an element
    expect(boundEvents.length).toBe(0);
  });
});

describe('dom.js - Tag Parsing and Code Highlighting', () => {
  beforeEach(() => {
    const fs = require('fs');
    const path = require('path');
    const vm = require('vm');
    const domCode = fs.readFileSync(path.resolve(__dirname, '../dom.js'), 'utf8');
    const sandbox = {
      chrome: global.chrome,
      document: global.document,
      window: global.window,
      showToast: vi.fn(),
      highlightElementOnPage: vi.fn(),
      removeHighlightFromPage: vi.fn(),
      console: console
    };
    vm.createContext(sandbox);
    vm.runInContext(domCode, sandbox);
    global.highlightCode = sandbox.highlightCode;
    global.unescapeHtmlEntities = sandbox.unescapeHtmlEntities;
  });

  describe('highlightCode with interactive tags (disabled)', () => {
    it('should not wrap opening tag in interactive-code-tag span', () => {
      const code = '<input id="account-search" class="SearchInput">';
      const highlighted = highlightCode(code, 'html');
      
      expect(highlighted).not.toContain('class="interactive-code-tag"');
      expect(highlighted).not.toContain('data-selector="#account-search"');
    });

    it('should not wrap closing tags in interactive-code-tag span', () => {
      const code = '</label>';
      const highlighted = highlightCode(code, 'html');
      
      expect(highlighted).not.toContain('class="interactive-code-tag"');
    });
  });
});

